export default {
  products: [
    {
      _id: "1",
      name: "Jordon air",
      category: "causual",
      image: "/images/img1.jpg",
      brand: "Nike",
      rating: 4.5,
      numReviews: 20,
      price: 200,
      countInStock: 10,
    },
    {
      _id: "2",
      name: "Fire Red",
      category: "causual",
      image: "/images/img1.jpg",
      brand: "Nike",
      rating: 5,
      numReviews: 20,
      price: 200,
      countInStock: 40,
    },
    {
      _id: "3",
      name: "space",
      category: "causual",
      image: "/images/img1.jpg",
      brand: "Nike",
      rating: 4.2,
      numReviews: 15,
      price: 200,
      countInStock: 5,
    },
    {
      _id: "4",
      name: "Jordon 5",
      category: "formal",
      image: "/images/img1.jpg",
      brand: "Nike",
      rating: 4.8,
      numReviews: 30,
      price: 200,
      countInStock: 9,
    },
    {
      _id: "5",
      name: "Jordon 1",
      category: "formal",
      image: "/images/img1.jpg",
      brand: "Nike",
      rating: 4.6,
      numReviews: 22,
      price: 200,
      countInStock: 15,
    },
  ],
};
